### ISSUE TITLE
where is run.sh???

### ISSUE THREAD

**Issue by 18242360613** [OniroAI/Universal-segmentation-baseline-Kaggle-Airbus-Ship-Detection#1]
This is a very meaningful work for me, it has helped me a lot. But I did not find the run.sh file, can you upload a copy again?

**Comment by voeykovroman** [comment]
Hey, numbers. Sorry for the late response. Added run.sh script, hope it'll be useful!

**Comment by 18242360613** [comment]
thanks for your replay. help me a lot.
